wget --no-check-certificate --continue -O GM4c_RNA_S7_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/Z0ZC5IoS3A5g4nZ/download
wget --no-check-certificate --continue -O slurm-22147718.out https://oc1.rnet.missouri.edu/index.php/s/Z7IOXItJmpmULUG/download
wget --no-check-certificate --continue -O GM4b_DNA_S2_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/kdWRBObH66Ixfq9/download
wget --no-check-certificate --continue -O md5sums.txt https://oc1.rnet.missouri.edu/index.php/s/pEflcJUmppG0foe/download
wget --no-check-certificate --continue -O dna_core_pipeline.json https://oc1.rnet.missouri.edu/index.php/s/rRlCV0QGdapBsPY/download
wget --no-check-certificate --continue -O multiqc_report.html https://oc1.rnet.missouri.edu/index.php/s/Fopjq5fT1webpvo/download
wget --no-check-certificate --continue -O GM1a_DNA_S6_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/HH1JrXWdEwE0TIH/download
wget --no-check-certificate --continue -O HW7TNDRXXSampleSheet.bare.csv https://oc1.rnet.missouri.edu/index.php/s/SFX6hIEqBq8xiqo/download
wget --no-check-certificate --continue -O GM1c_DNA_S4_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/aLNBesZMJ03OqOm/download
wget --no-check-certificate --continue -O GM1c_RNA_S10_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/A8ACF9C4QKp13Ko/download
wget --no-check-certificate --continue -O GM1c_RNA_S10_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/TqvVz116zf0ISwF/download
wget --no-check-certificate --continue -O GM4b_RNA_S8_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/p5S7IHH23Ii9hRy/download
wget --no-check-certificate --continue -O GM4a_RNA_S9_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/3WJLcls8p8XiFEl/download
wget --no-check-certificate --continue -O GM4c_RNA_S7_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/hpSBhFyxSD8F5D1/download
wget --no-check-certificate --continue -O meta.zip https://oc1.rnet.missouri.edu/index.php/s/wxstLdRMqb6oxuI/download
wget --no-check-certificate --continue -O GM1b_DNA_S5_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/Wp7zIUuzW1d0dFD/download
wget --no-check-certificate --continue -O GM1b_RNA_S11_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/axOEp9QGFlqJyQf/download
wget --no-check-certificate --continue -O GM4a_DNA_S3_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/iZilJLUP0EUUryK/download
wget --no-check-certificate --continue -O GM4c_DNA_S1_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/hgHpfLJZiNLM2Er/download
wget --no-check-certificate --continue -O GM4b_RNA_S8_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/cqbSH7ylZVt7hrV/download
wget --no-check-certificate --continue -O GM1c_DNA_S4_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/t6ArCtES2LYDmY3/download
wget --no-check-certificate --continue -O GM4b_DNA_S2_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/Z5GbizjtENPU3E7/download
wget --no-check-certificate --continue -O GM4a_RNA_S9_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/uYwm8nvzU0judT1/download
wget --no-check-certificate --continue -O GM1a_RNA_S12_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/s77cimEzRGtI1o7/download
wget --no-check-certificate --continue -O GM1a_DNA_S6_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/PZjLm39mWcD375s/download
wget --no-check-certificate --continue -O GM4a_DNA_S3_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/kUygTqZz1Khvv2C/download
wget --no-check-certificate --continue -O multiqc_data.zip https://oc1.rnet.missouri.edu/index.php/s/DyNDeXGlL4ijKhX/download
wget --no-check-certificate --continue -O GM1b_DNA_S5_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/Kjz2SurjQZsESff/download
wget --no-check-certificate --continue -O GM1b_RNA_S11_R1_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/2dK3VViCRhU3jNi/download
wget --no-check-certificate --continue -O HW7TNDRXXSampleSheet.csv.orig https://oc1.rnet.missouri.edu/index.php/s/FVCpR3sMNtiLZ3F/download
wget --no-check-certificate --continue -O GM1a_RNA_S12_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/xlXZhUdl0zZzzEc/download
wget --no-check-certificate --continue -O GM4c_DNA_S1_R2_001.fastq.gz https://oc1.rnet.missouri.edu/index.php/s/DTP1Gjyx26yGEbq/download
